Add extended API functions
Metis-Team/mts_marker pull request #69
Opened 2023-05-13 17:10 UTC by PhILoXs

**When merged this pull request will:**
- Implement #68 

### Added the following APIs
- getAllMarkers
- getMarkerConfig
- getMarkerScale
- getMarkerPos
- getPlayerUID
- setMarkerScale
- setMarkerScaleLocal

2023-05-13 18:15 UTC, Timi007 requested changes

2023-05-13 18:15 UTC, Timi007 commented on addons/markers/functions/fnc_setMarkerScaleLocal.sqf
> + *      Sets the new marker scale. (Same as vanilla setMarkerSizeLocal)
```suggestion
 *      Sets the scale/size of marker. (Same as vanilla setMarkerSizeLocal)
```

2023-05-13 18:22 UTC, PhILoXs commented on addons/markers/functions/fnc_getPlayerUID.sqf
as of generateUniquePrefix playerUID is used

2023-05-13 18:23 UTC, PhILoXs commented on addons/markers/functions/fnc_getPlayerUID.sqf
> + *      ["mtsmarker#123/0/1"] call mts_markers_fnc_getPlayerUID
as of generateUniquePrefix playerUID is used

2023-05-13 18:23 UTC, PhILoXs commented on addons/markers/functions/fnc_getPlayerUID.sqf
> + *      Returns PlayerUID from marker prefix.
as of generateUniquePrefix playerUID is used

2023-05-13 18:24 UTC, PhILoXs commented on addons/markers/functions/fnc_getMarkerPos.sqf
> +getMarkerPos [format["%1_frame", _namePrefix], _preserveElevation];
[0,0,0] is returned if marker does not exists

2023-05-13 19:04 UTC, PhILoXs commented on addons/markers/functions/fnc_getPlayerUID.sqf
> + *      STRING - PlayerUID or -1 if it isn't an editale Metis marker.
as of generateUniquePrefix playerUID is used
spelling and quotes are corrected

2023-05-13 19:06 UTC, PhILoXs commented on addons/markers/functions/fnc_getMarkerScale.sqf
> +(GVAR(namespace) getVariable _namePrefix) param [3]
The default return is [0,0], but we are working only with one scale number, so the default behavior is 0. This behavior is now documented inline.

2023-05-13 19:59 UTC, Timi007 requested changes

2023-05-13 19:59 UTC, Timi007 commented on addons/markers/functions/fnc_getMarkerConfig.sqf
> +(GVAR(namespace) getVariable _namePrefix) param [1]
```suggestion
(GVAR(namespace) getVariable [_namePrefix, []]) param [1, []]
```

2023-05-13 19:59 UTC, Timi007 commented on addons/markers/functions/fnc_getPlayerUID.sqf
> +((_namePrefix splitString "/") param [1])
```suggestion
(_namePrefix splitString "/") param [1, "-1"]
```

2023-05-13 20:11 UTC, Timi007 submitted a review, later dismissed

2023-05-13 20:14 UTC, Timi007 commented
Don't forget to document the new functions in the wiki.

2023-07-15 15:02 UTC, Timi007 approved these changes

2023-07-15 15:02 UTC, merged